services:
  - type: web
    name: golfpool-backend
    env: node
    buildCommand: PUPPETEER_SKIP_DOWNLOAD=true npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
