services:
  - type: web
    name: golfpool-backend
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium"
